### ISSUE TITLE
YQ which one to use?

### ISSUE THREAD

**Issue by dan-decoder** [andrei-pavel/bash-boilerplate#1]
Hi,

there are apperantly two yq, one is a wrapper for jq written in python (https://github.com/kislyuk/yq). The other more adult is a standalone tool written in Go (https://github.com/mikefarah/yq).
I was only able to get the binaries of the yq go-version, but there is no "-r" but only a "r" parameter, which leads in both cases to an error, when I try to parse the sample config of the hello_world.

Could you please let me know which yq I have to use and if its possible for you to let also the version written in GO work with your scripts?

Thanks a lot and regards,
Dan

**Comment by andrei-pavel** [comment]
Hi,

Thank you for taking interest in this project.

The `-r` in the python yq outputs raw data which only takes effect for target data with primitive types.

```
$ yq -r .data.this ./config.yaml
works!
```
```
$ yq .data.this ./config.yaml
"works!"
```
I can't tell you why this is necessary in `yaml-to-env`, I'll have to take a look to see if it can be removed.

That is one course of action. The other is to add support for `yq`s that are generally missing the `-r` flag. I'm currently caught in something, I'll do this by next week.

I love Go as a language and I would choose it or tools written in it over Python anytime, but personally I wouldn't switch to an alternative tool that''s missing a lot of features. Especially since counterpart `jq` and `xq` are also missing in Go?!

The `yq` I usually use can be installed through `pip3 install yq`.

```
$ yq --version
yq 2.10.1
```
But older versions should work as well.

**Comment by dan-decoder** [comment]
Hi Andrei,

thanks for your reply.

As I'm using your boilerplate in a very restricted corporate environment I might need to go with a bash only solution.
Otherwise I got some hurdles to get the yq installed on the systems where I got my script running.

A pretty promising peace of code what I found was this: https://stackoverflow.com/a/21189044

Maybe you can make use of this too and it would do the same job  for your project without any external prerequisites.

Thanks and regards,
Dan

**Comment by andrei-pavel** [comment]
Will have an attempt at the bash-only YAML parsing.

I'm also using it succesfully in a closed-source environment. For very branched out scripts, variable leaks become hard to control, but that's just something that's specific to bash in general rather than to this boilerplate.

If Go is more in your grasp, here's [a repo](https://github.com/jojomi/go-script) I always wanted to try. That plus [go-yaml](https://github.com/go-yaml/yaml) should do the trick.

Cheers!

**Comment by andrei-pavel** [comment]
The Go version is appalingly designed. It's missing core features that are present in `jq`. The python `yq` and the python `xq` maintain compatiblity with `jq` in regards to functions like `to_entries` that are needed for this kind of parsing. The author doesn't even bother to answer people who need these commands[1]. They also have the same invocation syntax such that it would be easy for me to now add support JSON configuration or XML configuration by simply replacing the invoked command. You'll see that the boilerplate prefers a newer version of `yq` by checking if the `walk` function is implemented, I couldn't even dream to hope for this in the Go `yq`. Some things are best left not reinvented.

I can't add support for the Go yq. If I were to add support for it, I would have to resort to `awk` for parsing which would remove the need for a `yq` altogether. I'm sorry.

To check if your version of `yq` is supported you can run `./lib/yaml-to-env ./config.yaml`, but you might have figured that out.

[1] https://github.com/mikefarah/yq/issues/60)

**Comment by andrei-pavel** [comment]
I've added support for systems without yq or with non-jq compliant versions of yq. Only top-level YAML fields will be converted as is also the case for older versions of yq that don't support the `walk()` function.
